### ISSUE TITLE
Switching to KeePass and Syncthing for password management

### ISSUE THREAD

**Issue by MartyLake** [rustysys-dev/ai03tutorial#2]
Hello Scott,
I don’t have an account on dev.to so I can’t answer, and I could not find your contact otherwise so excuse the innappropriateness of using GHissues for contacting you.

You mentionned on https://dev.to/rusty_sys_dev/switching-to-keepass-and-syncthing-for-password-management-1klh disappearing `.stfolder`. Maybe you found out already, but as mentionned https://github.com/syncthing/syncthing-android/issues/1396 and https://forum.syncthing.net/t/disappearing-stdfolder-in-android/14395/3 it’s due to vendor OS having "cleanup" apps deleting empty folders in the system. You can either disable such "cleanup" apps, and create a few bytes text file inside your `.stfolder` to prevent spurious deletion.

Best,

**Comment by rustysys-dev** [comment]
@MartyLake
Hey thanks for reading my post!! and also I didn't know about this... it is possible that is my issue! thank you for the heads up!!
